---

- name: Check steamcmd exists
  ansible.builtin.stat:
    path: "{{ steamcmd_path }}/steamcmd.sh"
  register: steancnd_file

- name: Download and unarchive steamcmd
  ansible.builtin.unarchive:
    src: "http://media.steampowered.com/client/steamcmd_linux.tar.gz"
    dest: "{{ steamcmd_path }}"
    remote_src: true
    mode: "0755"
  when: not steancnd_file.stat.exists

#TODO: Фикс костыль
- name: Start steamcmd
  ansible.builtin.command: "{{ steamcmd_path }}/steamcmd.sh +quit"

- name: Install screen package
  ansible.builtin.apt:
    name: "screen"
    state: present
    update_cache: true